name: cleanup
description: 'Cleanup docker and other build resources'
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        REPOSITORY=${REPOSITORY:-$IMAGE_NAME}
        df -h
        
        docker image -a
        docker images -a | grep "${IMAGE_TAG}" | awk '{print $3}' | sort -u | xargs -r docker rmi -f
        docker image -a
        df -h
        
        echo "Remove Dangling..."
        docker images -f dangling=true | grep -v "IMAGE" | awk '{print $3}' | xargs -r docker rmi -f
        df -h
        
        echo "Remove old builder cache"
        docker builder prune -f --filter "until=120h"
        df -h
